name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: ${{ secrets.DOCKER_NAME }}
      PKG_VERSION: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
      - name: echo
        run: echo $PKG_VERSION
      - name: BUILD DOCKER IMAGE
        run: docker build . --file Dockerfile --tag $APP_NAME:$PKG_VERSION
      - name: DOCKER LOGIN
        run: docker login -u=${{ secrets.DOCKER_LOGIN }} -p=${{ secrets.DOCKER_PASSWORD }}
      - name: PUSH DOCKER IMAGE
        run: docker push $APP_NAME:$PKG_VERSION
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          envs: APP_NAME, PKG_VERSION
          script: |
            docker pull $APP_NAME:$PKG_VERSION
      - uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_ID }}
          webhook_token: ${{ secrets.DISCORD_PW }}
          color: "#48f442"
          username: "Github Action Hook"
          message: ${{ secrets.DOCKER_NAME }} Projesini Güncelledim ve Sunucuya Koydum. Sana Zahmet Update Yaparsın Artık!
